version: '3'

volumes:
  minio-data:
    driver: local

services:
  minio:
    image: minio/minio:latest
    container_name: 'online_cinema-minio'
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_ACCESS_KEY}
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - minio-data:/minio
    command: server ~/minio --console-address :9090

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: "online_cinema-redis"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - cache:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass emFxMUBXU1g=