spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    url: jdbc:postgresql://localhost:5432/onlineCinema?currentSchema=onlineCinema
