spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineCinema
    username: postgres
    password: zaq1@WSX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  override-with-generic-response: false